### PR TITLE
Update main script in package json

### LINKED ISSUE #159: JS: Packaging help
Our current packaging up of the JS is poor in a number of ways. First and foremost: the `main` script.

https://github.com/vegaprotocol/api/blob/d9e0edae3c3e2d5c4255958c8e063cbb33a57a58/js/package.json#L5-L10

`main` is set to `bundle.index.js` for a reason I'll go in to later. However trying to import the `browserified` bundle in [vegaprotocol/console](https://github.com/vegaprotocol/console) doesn't work. Because it's browserified, which isn't what we need over there.

# Our current problem
We're trying to remove our usage of the [prepareX](https://docs.testnet.vega.xyz/docs/api-howtos/submit-order/#4-prepare-a-submit-order-message) endpoints. Previously we had no way of making protos for the wallet server to sign, but this api repo gives us that, so we're doing a spike to try it out

```bash
yarn add @vegaprotocol/vega-grpc
```

Works fine, and 
```typescript
import { vega } from '@vegaprotocol/vega-grpc'
// ...
const order = new vega.OrderSubmission()
order.setPartyId('1234')
```

In that example above, Intellij / VSCode / etc will correctly show the types and autocomplete. However when we get to actually running it in the browser, it won't bundle (will paste the error in a second)

Importing from '@vegaprotocol/vega-grpc/index' does work though?

## Easy! Just remove that `main` declaration
Yes. This will fix it. The reason that Browserify bundle is there at all is when it comes to signing code using Tweetnacl to sign stuff, we turned out to need `Buffer` from node. Which leads to other issues (e.g. https://github.com/dchest/tweetnacl-js/issues/59). However we're not using this functionality at the moment - so removing the `main` declaration is probably the way to go

## Related
Also the weird mix of Typescript & JS is a little odd. We should fix that - but that's a separate issue.

### PR DESCRIPTION
**Pull request by edd**
Closes #159 by stopping setting the bundled, browserified output as the `main` script

- Remove `browserify` dep
- Noop `build:browser`
- Remove `build:browser` from `build`
- Update `main` to `index.js`
- delete `bundle/index.js`

### CODE REVIEW

**Comment by ashleyvega** [comment]
@edd If we're no longer building `bundle/index.js`, should that file be deleted? If not, might it become stale?

**Comment by edd** [comment]
Yes we should

**Review by ashleyvega — APPROVED** [review]
LGTM

**Comment by edd** [comment]
@fkondej will this automatically publish if we merge it?

**Comment by fkondej** [comment]
@edd if you are talking about the release, then you need to add a tag, e.g.: https://github.com/vegaprotocol/api/blob/develop/.github/workflows/javascript-release.yml#L7

**Pull request merged**
