### PR TITLE
Add tx decode

### PR DESCRIPTION
**Pull request by edd**
Adds some functions & tests to demonstrate encoding and decoding transactions in JavaScript/TypeScript. Note that as browsers can't directly call GRPC endpoints, this is only currently useful in specific contexts - namely decoding a transaction from a block fetched from Tendermint's RPC endpoint, or encoding an order/other transaction so that it can be passed to a [wallet](https://github.com/vegaprotocol/go-wallet) for signing & submission. 

The TS/JS compilation could be neater, but the branch is already useful so.. tidyup: later?

### CODE REVIEW

**Comment by edd** [comment]
I've rebased on `master` but not `develop` so this PR needs a rebase, :hourglass:

**Comment by ashleyvega** [comment]
@edd I can fix the conflicts...

**Comment by edd** [comment]
> @edd I can fix the conflicts...

It was a mess I created, so I felt obliged to tidy it up. Done!

**Comment by ashleyvega** [comment]
@edd A test is failing ...

**Comment by ashleyvega** [comment]
Also, could we use `git merge ... ; git push origin add-tx-decode` rather than `git rebase ... ; git push --force origin add-tx-decode` please? It makes collaborating easier if the past stays put.

**Comment by edd** [comment]
> Also, could we use `git merge ... ; git push origin add-tx-decode` rather than `git rebase ... ; git push --force origin add-tx-decode` please? It makes collaborating easier if the past stays put.

I will do that on this repo in future. It also would have avoided a lot of this mess.

**Review by ashleyvega — APPROVED** [review]
LGTM

**Pull request merged**
