### PR TITLE
CI: Ensure all manually created PRs are linked to an Issue

### LINKED ISSUE #300: Add new github action to verify all PRs have linked issues
In order to visualise all the work we have in progress on the project board and ensure that all work in PRs has an associated issue that can be seen, read and understood, we will add an [action](https://github.com/hattan/verify-linked-issue-action/blob/master/example/pr_verify_linked_issue.yml) to validate that all PRs are linked to an issue.

This will help to ensure that we are focusing on the right work for the time and that each work item can be tested as required against acceptance criteria captured in the issue.

**Known limitations of this action:**
- There must be a space after the issue number (ie "#num " not "#num".) This is due to the way the RegEx is structured and will be resolved in a future release.
- The Issue reference by # needs to be in the body, we don't currently look in the title. That is a future enhancement.

### PR DESCRIPTION
**Pull request by gordsport**
As per the description in #300 this adds an action to verify that all PRs have linked issues noted in the body of the PR.

closes #300

### CODE REVIEW

**Comment by ashleyvega** [comment]
@gordsport What about auto-generated PRs, e.g. from Whitesource Renovate (#299)

We may want to add a PR title exclusion (`Update dependency *`) or a branch exclusion (`renovate/*`) if possible.

**Comment by gordsport** [comment]
@ashleyvega - could we have a conversation on this?

**Review by ashleyvega — APPROVED** [review]
LGTM

**Comment by gordsport** [comment]
@ashleyvega Updated to an if statement rather than branches-ignore as the latter looks at the target branch.

**Review by fkondej — APPROVED** [review]

**Pull request merged**
